# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171103_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/no-avatar-icon.jpg', null=True, upload_to='avatars'),
        ),
    ]
