# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '\u041a\u043d\u0438\u0433\u0430', 'verbose_name_plural': '\u041a\u043d\u0438\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books'),
        ),
    ]
