# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171005_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='post.Post'),
        ),
    ]
